### ISSUE TITLE
文章翻译：赢在Apache-项目独立性

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/open-source-articles#13]
1) Project Independence 项目独立性
 https://s.apache.org/CE0V

https://shimo.im/docs/c7nkM4nD7cIOimMm

**Comment by bastamon** [comment]
@tedliu1 这个issue为什么open是2018年的，最近才添加到To do，是不是真的还没人翻译？时间这么久我感觉难以置信，想译

**Comment by bastamon** [comment]
by @bastamon

**Comment by bastamon** [comment]
Complete **Success at Apache: Project Independence**

**Comment by bastamon** [comment]
Complete **Success at Apache: Project Independence**

https://shimo.im/docs/c7nkM4nD7cIOimMm/ 「Project_Independence」，可复制链接后用石墨文档 App 或小程序打开
