### ISSUE TITLE
文章翻译：赢在Apache-只有胡萝卜，没有大棒

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/open-source-articles#14]
2) All Carrot and No Stick 只有萝卜，没有棒子
 https://s.apache.org/ykoG 

https://shimo.im/docs/1MKxIETVBac6dZHY

**Comment by stronghx** [comment]
@已完成，待审核。

**Comment by stronghx** [comment]
@tedliu1 已完成，待审核。
