### ISSUE TITLE
转载：2019 成都 Web 全栈大会

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/open-source-articles#143]
https://mp.weixin.qq.com/s/anZ-t7NixLxPH7eK4niYCA

**Comment by cynbarby** [comment]
开头文字：

开源活动推荐

为了满足广大开源爱好者线下面基和共同进步的需求，开源社特推出开源活动板块，网罗天下开源好活动，推荐给爱学习求上进的小伙伴！感兴趣的小伙伴可以关注我们的活动推荐，我们也欢迎大家提供线索给我们哦。

本期活动推荐：xxxx 详情请看文内介绍

**Comment by TechQuery** [comment]
https://mp.weixin.qq.com/s/FxQk15TV147oILH2R3f9fg
