### ISSUE TITLE
文章翻译：赢在Apache-干了再说，贡献者无条件的爱

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/open-source-articles#17]
5) JFDI --the unconditional love of contributors JFDI--干了再说，贡献者无条件的爱
 https://s.apache.org/4pjM

https://shimo.im/docs/3ZEmFeLi9VAiRBnn

**Comment by stronghx** [comment]
@tedliu1 翻译完毕，请审核。

**Comment by tedliu1** [comment]
好的👌

Best regards,

Ted Liu, 
Co-founder & chairman of the board, KAIYUANSHE | ASF Member, Sponsor Ambassador, Incubator PMC Member 
 
  2019 年 6 月 7 日周五 21:43，stronghx<notifications@github.com> 写道：   
@tedliu1 翻译完毕，请审核。

**Comment by tedliu1** [comment]
@stronghx @ch-shumin 审核完毕，待编辑！
