### ISSUE TITLE
文章翻译：赢在Apache-精英治理与我

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/open-source-articles#18]
6) Meritocracy and Me 精英治理与我
 https://s.apache.org/tQQh 

https://shimo.im/docs/FyDs2yArnLM1jj82

**Comment by stronghx** [comment]
@tedliu1 你好，文章已经翻译完毕，请帮忙审核，谢谢。

**Comment by stronghx** [comment]
@tedliu1  “ pick the brains of people ”原来是和对方交流的意思，学习了。

**Comment by tedliu1** [comment]
是“请教”的意思。
Best regards, 

Ted LiuCo-Founder & Chairman of the Board of Directors, KAIYUANSHE |ASF Member, Sponsor Ambassador, IPMC Member, Echarts Podling Mentor
Mail: tedliu@apache.org
 

    On Tuesday, June 4, 2019, 5:30:26 PM GMT+8, stronghx <notifications@github.com> wrote:  
 
 
@tedliu1 “ pick the brains of people ”原来是和对方交流的意思，学习了。
