### ISSUE TITLE
文章翻译：赢在Apache-学习如何建立一个更强的社区

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/open-source-articles#19]
7) Learning to Build a Stronger Community 学习如何建立一个更强的社区
 https://s.apache.org/x9Be

https://shimo.im/docs/9jetlTZeNsYlU6vt

**Comment by stronghx** [comment]
@tedliu1 文章已经翻译完毕，请审核。

**Comment by stronghx** [comment]
这篇文章比较难懂，作者用了一些术语，不容易理解。比如他说到的“Champion“，并不是我们常说的“冠军”，而是维护者或助理的意思，就是帮助孵化项目找投资人、答疑解惑。
