### ISSUE TITLE
文章翻译：在开源项目中如何成长为一名团队带头人

### ISSUE THREAD

**Issue by lijiangsheng1** [kaiyuanshe/open-source-articles#2]
原文链接：

[How I became a project team leader in open source](https://opensource.com/article/17/2/my-open-source-story-leader)

**Comment by cynbarby** [comment]
Elsa已经认领，等待文档中。。

**Comment by stronghx** [comment]
https://shimo.im/docs/g2RsSYQTW2MZtuKw

**Comment by stronghx** [comment]
@lijiangsheng1 翻译完毕，请审核。
