### ISSUE TITLE
文章翻译：赢在Apache-精英治理

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/open-source-articles#20]
8) Meritocracy 精英治理
https://s.apache.org/DiEo 

https://shimo.im/docs/E6Dkds9neoUY9PsB

**Comment by Davidlikeit** [comment]
我来这篇吧

**Comment by Davidlikeit** [comment]
@tedliu1  麻烦ted帮我加个 已完成 label

**Comment by cynbarby** [comment]
已发布。https://mp.weixin.qq.com/s?__biz=MzA5MTA2NDA5MQ==&mid=2655311230&idx=1&sn=eb426028f7398c2cc58adf5e958b7100&chksm=8bb2670abcc5ee1c28b2bcb1273d006f9f652bef8351f135ba66b402bd2aa948d1d4b48f3c69#rd
