### ISSUE TITLE
文章翻译：赢在Apache-搔自己的痒

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/open-source-articles#21]
10) Scratch your own itch. 搔自己的痒
 https://s.apache.org/Apah 

https://shimo.im/docs/2ZPjJ9njnDsdA0co

**Comment by cynbarby** [comment]
已发布。https://mp.weixin.qq.com/s?__biz=MzA5MTA2NDA5MQ==&mid=2655311164&idx=1&sn=ceff03c43ddada7fceecf17e5a2c31fc&chksm=8bb26748bcc5ee5ebeaed167e4dd8b7d60bce98116d9d5748cf447a4f98a7946831a9234d349#rd
