### ISSUE TITLE
文章翻译：赢在Apache-一个漫长、奇特(以及伟大)的旅程

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/open-source-articles#22]
11) What a Long Strange (and Great) Trip It's Been 一个漫长、奇特(以及伟大)的旅程
 https://s.apache.org/gVuN 

https://shimo.im/docs/TiP7XGTI1uYzzODn

**Comment by tedliu1** [comment]
放弃认领

**Comment by stronghx** [comment]
翻译完毕，等待审核。
@tedliu1
