### ISSUE TITLE
文章翻译：赢在Apache-一位菜鸟贡献者成长的故事

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/open-source-articles#23]
12) A Newbie's Narrative 一位新手的独白
 https://s.apache.org/A72H 

https://shimo.im/docs/ZfkB62SiFAUrjQ1e

**Comment by tedliu1** [comment]
@lijiangsheng1 文章已经翻译完成，内容较多，其中有关于大数据的技术名词不少，请费心审阅。谢谢。

**Comment by cynbarby** [comment]
已发布。https://mp.weixin.qq.com/s?__biz=MzA5MTA2NDA5MQ==&mid=2655311267&idx=1&sn=222e57170af49715c907238586349971&chksm=8bb267d7bcc5eec1b57b1f8f52db111c59be0eced12e4d660a7fd6c3c2f8ec2164309549330d&token=1559797812&lang=zh_CN#rd
