### ISSUE TITLE
文章翻译：赢在Apache-工作压力山大之下，同时贡献开源

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/open-source-articles#24]
13) Contributing to Open Source even with a high-pressure job 工作压力山大之下，同时贡献开源
 https://s.apache.org/lM9O 

https://shimo.im/docs/eKUEBqiOv1g8bf88

**Comment by lijiangsheng1** [comment]
翻译的内容非常的棒！👍 @tedliu1 

请把石墨文档中的英文去掉。

**Comment by cynbarby** [comment]
Done.https://mp.weixin.qq.com/s?__biz=MzA5MTA2NDA5MQ==&mid=2655311087&idx=1&sn=e138a656de763c64acbab838ec7a46de&chksm=8bb2669bbcc5ef8d05270d7cd603f8c6a1ca0d0ec685c091c7e94de587b477d251a31194f9bd#rd
