### ISSUE TITLE
文章翻译：世界顶级企业开源故事系列：微软的开源故事-开源如何兴旺发展？

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/open-source-articles#25]
The Open Source Program at Microsoft: How Open Source Thrives

https://github.com/todogroup/guides/blob/master/casestudies/microsoft.md
All content is licensed under CC-BY-SA 4.0.

石墨文档：https://shimo.im/docs/sROMF7tqgbEpTfFc

**Comment by lijiangsheng1** [comment]
能否将石墨上的英文去掉了呢？ 这会给媒体组的同事带来很大的困扰。

**Comment by tedliu1** [comment]
已经移除英文原文，并将通知媒体组排期发布。 @lijiangsheng1

**Comment by tedliu1** [comment]
校对完成，请排期发布 @媒体组成员

**Comment by cynbarby** [comment]
已发布。
