### ISSUE TITLE
文章翻译：世界顶级企业开源故事系列：Salesforce 的开源故事

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/open-source-articles#26]
https://github.com/todogroup/guides/blob/master/casestudies/salesforce.md
All content is licensed under CC-BY-SA 4.0.

https://shimo.im/docs/FazmGt4wJmQNWIl7

**Comment by lijiangsheng1** [comment]
建议将文档中的英文原文去掉。

**Comment by tedliu1** [comment]
已经移除英文原文，并将通知媒体组排期发布。 @lijiangsheng1

**Comment by tedliu1** [comment]
校对完成，请排期发布 @媒体组成员

**Comment by cynbarby** [comment]
已发布。

**Comment by cynbarby** [comment]
已发布。https://mp.weixin.qq.com/s?__biz=MzA5MTA2NDA5MQ==&mid=2655311203&idx=1&sn=cfdac322ba71b1e5e6b44f084523d74e&chksm=8bb26717bcc5ee01e7d67f7ed794adb77d13cefcc4d7b88f18ef03eccca0391a08b2d112b5f7#rd
