### ISSUE TITLE
演讲整理：庄表伟—古典DevRel和现代DevRel

### ISSUE THREAD

**Issue by lijiangsheng1** [kaiyuanshe/open-source-articles#27]
直接编辑即可。

石墨地址： [https://shimo.im/docs/3GQZGE54pUI1QWs8](https://shimo.im/docs/3GQZGE54pUI1QWs8)

**Comment by zhuangbiaowei** [comment]
done

**Comment by cynbarby** [comment]
Done。https://mp.weixin.qq.com/s?__biz=MzA5MTA2NDA5MQ==&mid=2655311112&idx=1&sn=91eaddb2372be0680238cc934073ce7f&chksm=8bb2677cbcc5ee6a29a4cee3ac22c73910ae665a596354a05567d7413adc58014ac8e0031d47#rd
