### ISSUE TITLE
演讲整理： 刘天栋:开源社区与项目激励机制的思考

### ISSUE THREAD

**Issue by lijiangsheng1** [kaiyuanshe/open-source-articles#3]
请基于以下速记：

[http://www.caict.ac.cn/pphd/zb/oscar2018/22pm/4/201803/t20180322_2242588.html](http://www.caict.ac.cn/pphd/zb/oscar2018/22pm/4/201803/t20180322_2242588.html)

完善内容。

**Comment by tedliu1** [comment]
啊，这个方式很赞哦！

Ted Liu 
 
  2018 年 3 月 23 日周五 16:02，适兕<notifications@github.com> 写道：   
Assigned #3 to @tedliu1.

**Comment by tedliu1** [comment]
[https://shimo.im/docs/jBnX2Bkb4yY8Ke1Y](url)

**Comment by tedliu1** [comment]
[](https://shimo.im/docs/jBnX2Bkb4yY8Ke1Y)

**Comment by tedliu1** [comment]
[https://shimo.im/docs/jBnX2Bkb4yY8Ke1Y](url)

**Comment by tedliu1** [comment]
https://shimo.im/docs/jBnX2Bkb4yY8Ke1Y

**Comment by lijiangsheng1** [comment]
@tedliu1  我又修改了一版，麻烦看看。没有问题的话，我就直接让媒体组发送了。

[https://shimo.im/docs/jBnX2Bkb4yY8Ke1Y](https://shimo.im/docs/jBnX2Bkb4yY8Ke1Y)

**Comment by tedliu1** [comment]
我修改完了，请 @lijiangsheng1 帮忙再审阅一下，谢谢。
https://shimo.im/docs/jBnX2Bkb4yY8Ke1Y
