### ISSUE TITLE
翻译：A Bitter Guide To Open Source 一份苦逼的开源指南

### ISSUE THREAD

**Issue by cynbarby** [kaiyuanshe/open-source-articles#34]
原文：https://medium.com/codezillas/a-bitter-guide-to-open-source-a8e3b6a3c1c4
译文：https://shimo.im/docs/LZdQMC9IiPchkXEE @lijiangsheng1 请审核。

**Comment by cynbarby** [comment]
已完成。

**Comment by tedliu1** [comment]
@cynbarby 已经发布的文章请 Close the Issue.
