### ISSUE TITLE
字幕翻译：Open Source vs. Closed Source Software

### ISSUE THREAD

**Issue by cynbarby** [kaiyuanshe/open-source-articles#37]
[https://www.youtube.com/watch?v=2q91vTvc7YE](url)

**Comment by TomQunChao** [comment]
https://shimo.im/docs/GrytyMi6gSwbIS1k/

**Comment by tedliu1** [comment]
@TomQunChao 已审阅完毕，并以评论方式做出相应修改建议 https://shimo.im/docs/GrytyMi6gSwbIS1k/

**Comment by tedliu1** [comment]
开源社公众号已发布
