### ISSUE TITLE
文章翻译：Announcing the CarGurus Open Source Fund

### ISSUE THREAD

**Issue by cynbarby** [kaiyuanshe/open-source-articles#38]
https://medium.com/cargurus-engineering-blog/announcing-the-cargurus-open-source-fund-519f97d9898

**Comment by bastamon** [comment]
已认领

**Comment by cynbarby** [comment]
# Announcing the CarGurus Open Source Fund
*Seth Woodworth*

I’m very pleased to announce a new initiative to support Free and Open Source Software (FOSS): the CarGurus Open Source Fund (OSF).

CarGurus engineers rely on FOSS projects to power our infrastructure. It runs our servers, lints our code, compiles our assets, and lets us build more, faster. And like all engines, FOSS projects need maintenance and support to continue running.

## Open Source Fund

Here at CarGurus, Senior Software Engineer Wei Croteau proposed giving back to these projects with an Open Source Fund. She organized an OSF committee of engineers experienced with FOSS projects. The group asked CarGurus engineers to submit FOSS projects; that were used at CarGurus, non-profit, and/or worked on by a CarGurus employee. From this list, the OSF Committee vetted the projects, and narrowed it down to nine projects to support in Q1 of 2019.

In the spirit of collaboration and bottom-up participation, a pool of $15,600 was dispersed across the 156 members of our engineering organization. Each engineer choose which project received their individual contribution of $100. On top of the pool of engineering directed funds, the OSF committee highlighted one project to give an additional $10,000. As the OSF continues, the pool available the engineering directed funds will increase. Each engineer will continue to choose a project to receive $100 per quarter.

## Projects we’re funding in the first quarter of 2019

Here are first projects we’re supporting as part of the CarGurus Open Source Fund:

* Babel — Ensuring that our JS libraries are forward and backward compatible for all of our users.
* FreeBSD — CarGurus doesn’t use much FreeBSD directly, but we benefit from the security and stability it provides the internet infrastructure, and we have engineers who volunteer for the project.
* GIT — Our distributed version control system of choice.
* Homebrew — The foremost package management platform for MacOS.
* Linux Kernel — The OS for over 1000 virtual machines running at CarGurus.
* Open Web Application Security Project (OWASP) — An unbiased source for best practices for web application security.
* RuboCop — A linter for ensuring our Ruby code quality.
* Webpack — The best solution for bundling JS, CSS, and other asset files.

## Highlight Project: Apache Software Foundation

And the highlight project for this quarter is the **Apache Software Foundation**.

Many engineering teams at CarGurus use projects maintained by the Apache Software Foundation (ASF). When polling the engineering teams about what FOSS projects have the most impact, a large number of those projects were from Apache. The ASF was officially organized 20 years ago to facilitate support and development of the Apache web server. It has since grown significantly, and now organizes hundreds of FOSS projects. A number of these projects are critical to our daily operations here at CarGurus, and we want to highlight the following two:

**Apache Kafka** is a massively scalable, fault-tolerant, distributed streaming platform used at CarGurus to process dealer inventory, site events, and site analytics. After having outgrown jgroups, Kafka allows us to reliably transport massive amounts of data, scale in response to demand, and facilitate low-latency access to data across the organization.

**Apache Airflow** is the DAG-based ETL scheduling framework that enables our data engineering teams to centralize the company’s data assets in timely, reliable fashion. It provides complex dependency management for modeling across hundreds of data sources, enables detailed introspection into status and timing, and powers our highly-concurrent distributed etl architecture.

Due to the massive amount of software and libraries from Apache that power CarGurus, the OSF committee has chosen them as our highlight project, and granted them an additional $10,000 on top of our engineers’ votes.

## On-going support

This isn’t the end for the Open Source Fund, but just the beginning. The OSF is engineer founded and engineer run. We have commitment and support from management for continued funding, and the amount we give each quarter will increase as we grow the size of our engineering team. We’ll be running another round of funding next quarter as part of our ongoing commitment to give back to the engineering community at large.

**Comment by bastamon** [comment]
https://shimo.im/docs/YPeqZp6fPRscIIOR/ 「Announcing_the_CarGurus_Open_Source_Fund」，可复制链接后用石墨文档 App 或小程序打开
翻译完成，等待校对

**Comment by bastamon** [comment]
@tedliu1 @cynbarby

**Comment by bastamon** [comment]
https://github.com/kaiyuanshe/open-source-articles/blob/cynbarby-patch-1/translation/Announcing_the_CarGurus_Open_Source_Fund.md

**Comment by tedliu1** [comment]
已审核完毕，并修改于石墨文档：https://shimo.im/docs/YPeqZp6fPRscIIOR/ 「Announcing_the_CarGurus_Open_Source_Fund」
