### ISSUE TITLE
文章翻译：The mysterious history of the MIT License

### ISSUE THREAD

**Issue by cynbarby** [kaiyuanshe/open-source-articles#47]
原文地址：https://opensource.com/article/19/4/history-mit-license

**Comment by bastamon** [comment]
by: @bastamon

**Comment by bastamon** [comment]
@tedliu1 @cynbarby ：已经译好，倒数第3段能力有限看不懂，有问题！！！

> For example, there is a 3-Clause BSD License and an older 4-Clause one, even though there is no explicit versioning.

https://shimo.im/docs/PxQC372jgMsVTarY/ 「The mysterious history of the MIT License」，可复制链接后用石墨文档 App 或小程序打开

**Comment by tedliu1** [comment]
@bastamon 请将石墨文档设为“公开分享，可读写”。

**Comment by tedliu1** [comment]
@tedliu1 审核中
