### ISSUE TITLE
原创：开源软件项目是否会被限制出口？

### ISSUE THREAD

**Issue by ch-shumin** [kaiyuanshe/open-source-articles#64]
作者：开源社 Ted Liu  
链接：https://shimo.im/docs/6sWwmJL8k7QPk5pM?from=singlemessage

**Comment by tedliu1** [comment]
Published.
原创：林诚夏
专家解读：开源软件项目是否会被限制出口?
https://mp.weixin.qq.com/s/_wmBHskWi5CCTjDWu6fMAg
