### ISSUE TITLE
翻译：LF Statement Regarding Huawei Entity List Ruling

### ISSUE THREAD

**Issue by ch-shumin** [kaiyuanshe/open-source-articles#65]
https://shimo.im/docs/CmxwseqKysEpqfsQ
翻译整篇文章

**Comment by cynbarby** [comment]
已认领。

**Comment by cynbarby** [comment]
翻译链接：https://shimo.im/docs/PzdkyBYboEKT0A6g

**Comment by tedliu1** [comment]
Published. 
权威答复：Linux基金会的回信来了！
https://mp.weixin.qq.com/s/UGpdQItcwPACe2k-rGSUuA
