### ISSUE TITLE
EAR 事件：开源社专家 CSDN 深度访谈录]

### ISSUE THREAD

**Issue by ch-shumin** [kaiyuanshe/open-source-articles#66]
https://shimo.im/docs/oIxv2NsJMvY6vvbz?from=groupmessage
编辑并发布，与CSDN公众号同步发布。

**Comment by tedliu1** [comment]
Initiated @sssuyx 
Author: 林诚夏
Edited by @ch-shumin 
Reviewed by @tedliu1
权威解读 GitHub、Apache 疑云：主流开源软件究竟是否会被闭源？
开源社微信公众号 https://mp.weixin.qq.com/s/wEzNmgtKgrFYg4PLxgq8XA
[CSDN](https://mp.weixin.qq.com/s?__biz=MjM5MjAwODM4MA==&mid=2650720752&idx=1&sn=79e5f38dc4ddb21591fd33bbbc5c1913&chksm=bea6b82389d131354662fab116cb3d909109f5336546dafef0fee624afee17454c521e24c4e7&mpshare=1&scene=1&srcid=&key=e37b65ef319f79ac224b0ac7a1f3488765d8701f89d8893fb41680a9daa03bc39097d6ab8f3be37887ae7dbdf55b3e84ab0ddb72ed7878dac314e754c6c22580ace5e80033edb41c7eda6de4e3bd4050&ascene=1&uin=MjU2MDM4ODc4MA%3D%3D&devicetype=Windows+10&version=62060739&lang=zh_CN&pass_ticket=rjgbG0KMs8sB20BeQ2BGd%2BvvJSYFmyCz6p7yybRwHaUbbBzTT0HyNsN3v%2F1Jj5uw)
