### ISSUE TITLE
原创：开源社走进高校活动携 TensorFlow 走进同济大学

### ISSUE THREAD

**Issue by ch-shumin** [kaiyuanshe/open-source-articles#67]
作者：李建盛老师
https://shimo.im/docs/TajFq252580Y3hwX
原创

**Comment by tedliu1** [comment]
Published: 
开源社走进高校活动携 TensorFlow 走进同济大学
https://mp.weixin.qq.com/s/ni6x_c55fSlKt9nkJsGMvQ
