### ISSUE TITLE
转载：活动| 来了，老弟 | 第五届阿里巴巴中间件性能挑战赛开始报名啦 

### ISSUE THREAD

**Issue by cynbarby** [kaiyuanshe/open-source-articles#69]
原文 https://mp.weixin.qq.com/s?__biz=MzU4NzU0MDIzOQ==&mid=2247486599&idx=1&sn=d61ba8324dcdfc3bd9fea1c7475c2b82&chksm=fdeb3ee7ca9cb7f1f7e217e3993af1be413627fe5ed3029ba5869f7badd0c3c302ab0301edf8&mpshare=1&scene=1&srcid=#rd

文章跳转活动用这个链接：https://tianchi.aliyun.com/markets/tianchi/aliware2019?spm=a2c41.12893024.0.0

主办方希望能和开源社联合推广，作为支持社区在活动那个也和赛题页做品牌logo展示。
如果主编审核后觉得微信公众号不能发布的话，在微博发布即可。

**Comment by tedliu1** [comment]
活动已经结束，我们一直没有发布。
