### ISSUE TITLE
文章翻译：A graduate degree could springboard you into an open source job

### ISSUE THREAD

**Issue by lijiangsheng1** [kaiyuanshe/open-source-articles#7]
一篇来自OpenSource.com的文章，关于开源求职的经验之谈。

[https://opensource.com/article/17/1/grad-school-open-source-academic-lab](https://opensource.com/article/17/1/grad-school-open-source-academic-lab)

**Comment by bastamon** [comment]
已认领

**Comment by bastamon** [comment]
https://shimo.im/docs/I9nbpkVDJXYJGgA5/ 《研究生学位能让更快你进入开源工作》，可复制链接后用石墨文档 App 或小程序打开

**Comment by bastamon** [comment]
已施工完毕，等待排版
@tedliu1 
https://shimo.im/docs/APke2qH7NF4NDFAa/ 《研究生学位能让更快你进入开源工作》，可复制链接后用石墨文档 App 或小程序打开或者查看makedown版本
https://github.com/bastamon/open-source-articles/blob/master/A_graduate_degree_could_springboard_you_into_an_open_source_job.md

**Comment by tedliu1** [comment]
开源社微信公众号已发布。
