### ISSUE TITLE
转载：企业开源指南：开源代码的使用 

### ISSUE THREAD

**Issue by cynbarby** [kaiyuanshe/open-source-articles#77]
转载自：Linux 中国
原文链接：https://mp.weixin.qq.com/s?__biz=MjM5NjQ4MjYwMQ==&mid=2664614296&idx=3&sn=60115c97a45f6f3079afc5637dff0a88&chksm=bdcef2de8ab97bc82f30cbfd94138b63325fb4c56c45ddfc082de9fbc70742653987fcd85cb6&mpshare=1&scene=1&srcid=#rd

Linux中国的格式不需要遵循，用我们自己的格式就好。

**Comment by tedliu1** [comment]
@ch-shumin 这篇已经发表了吗？
