### ISSUE TITLE
从开源小白到 Apache Member ，阿里工程师的成长笔记

### ISSUE THREAD

**Issue by ch-shumin** [kaiyuanshe/open-source-articles#83]
转载：https://mp.weixin.qq.com/s/v2e_WCIdwzNisaKRbebxsw
Apache Roadshow China

2015年10月，我有幸在北京参加了 Apache Roadshow China，算是第一次和Apache 基金会有了亲密接触。在大会上亲眼目睹了时任 Apache 基金会主席 Brett Porter、Apache 基金会副总裁 Niclas Hedhman 等大佬们的演讲，以及在 Panel Disussion 里面，几位大佬和几位来自中国的 Apache 成员的一起探讨社区领导的开发流程等。

当时觉得自己离他们似乎非常遥远。2015年的时候，国内参与开源  Apache 社区的几乎全是在外企工作的华人。而如今来看，国内公司参与开源的程度已经显著地提升。这次参与中国路演，有幸和 Niclas heldman 做了一些交流，我问了他一个问题：我正在参与 Tomcat 社区，如何才能成为 committer？他给了我一些至今对我影响依然非常深远的建议：参与社区讨论，从简单的新手任务入手修复 bug，以及参与 release vote。而这么多年过去了，这些建议依旧适用。

**Comment by tedliu1** [comment]
舒美女，这篇转载我想加上开源社引言哈！

Best regards,

Ted Liu, 
Co-founder & chairman of the board, KAIYUANSHE | ASF Member, Sponsor Ambassador, Incubator PMC Member 
 
  2019 年 6 月 11 日周二 19:52，ch-shumin<notifications@github.com> 写道：   
转载：https://mp.weixin.qq.com/s/v2e_WCIdwzNisaKRbebxsw
Apache Roadshow China

2015年10月，我有幸在北京参加了 Apache Roadshow China，算是第一次和Apache 基金会有了亲密接触。在大会上亲眼目睹了时任 Apache 基金会主席 Brett Porter、Apache 基金会副总裁 Niclas Hedhman 等大佬们的演讲，以及在 Panel Disussion 里面，几位大佬和几位来自中国的 Apache 成员的一起探讨社区领导的开发流程等。

当时觉得自己离他们似乎非常遥远。2015年的时候，国内参与开源  Apache 社区的几乎全是在外企工作的华人。而如今来看，国内公司参与开源的程度已经显著地提升。这次参与中国路演，有幸和 Niclas heldman 做了一些交流，我问了他一个问题：我正在参与 Tomcat 社区，如何才能成为 committer？他给了我一些至今对我影响依然非常深远的建议：参与社区讨论，从简单的新手任务入手修复 bug，以及参与 release vote。而这么多年过去了，这些建议依旧适用。
