### ISSUE TITLE
文章翻译：4个开源项目命名的意见

### ISSUE THREAD

**Issue by lijiangsheng1** [kaiyuanshe/open-source-articles#9]
来自OpenSource.com的一篇文章：

[Choosing project names: 4 key considerations](https://opensource.com/article/18/2/choosing-project-names-four-key-considerations)

**Comment by cscmucmm** [comment]
认领

**Comment by cynbarby** [comment]
https://shimo.im/invite_link_show/7eXkT0vvlFcAW5Kd0qFEz0CyDjI34Orm0ZL9cQgj?inviter=D3XEPK0 ，译者：文涛
